# STAGE 1 - Builder (Workplace)
FROM node:20 AS builder

WORKDIR /app

# dependencies + code
COPY package*.json ./
RUN npm install

COPY . .

# (real world: npm run build)


# STAGE 2 - Final (Production Image)
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app .

CMD ["node", "app.js"]
